services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: intelligent_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  postgres_test:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: intelligent_order_assistant_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
    - ./docker/postgres_test/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data: