"""add product constraints

Revision ID: 33489611b00a
Revises: d917fc8bf88c
Create Date: 2026-08-31 20:06:47.913845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33489611b00a'
down_revision: Union[str, Sequence[str], None] = 'd917fc8bf88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_products_price_non_negative', 'products', 'price >= 0')
    op.create_check_constraint('ck_products_stock_non_negative', 'products', 'stock >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_stock_non_negative', 'products', type_='check')
    op.drop_constraint('ck_products_price_non_negative', 'products', type_='check')
    # ### end Alembic commands ###
